name: Dummy Deploy Action

on:
  push:
    branches:
      - 'test-cache'
    tags:
      - 'Releases/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: test.txt
          key: ${{ runner.os }}-text-${{ hashFiles('test.txt') }}
          restore-keys: ${{ runner.os }}-text-
      - name: Echo if cache hit
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo 'cache hit!!!!!'
      - name: Show text
        run: cat test.txt